####Write confusion matrix in CSV file with following condition1 :
1. Heading and 1st column should be class name
2. The data goes row wise i.e. 1st row will have detail of class1 classified to which classes

In [3]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

evaluation = pd.read_csv("evaluation.csv", header = 0)
evaluation= evaluation.drop(evaluation.columns[0], axis = 1)
classes = list(evaluation.columns)
print(classes)

evaluation = genfromtxt('evaluation.csv', delimiter=',')
print(evaluation)


evaluation = np.delete(evaluation, 0, 0)
evaluation = np.delete(evaluation, 0, 1)
print(evaluation)

Observed = evaluation

['Media', 'S', 'E']
[[nan nan nan nan]
 [nan 26. 13.  5.]
 [nan 20. 29.  7.]]
[[26. 13.  5.]
 [20. 29.  7.]]


In [4]:
Expected = np.empty_like(Observed)
total = np.sum(Observed)
for idx, x in np.ndenumerate(Observed):
    Expected[idx] = ((sum(Observed[idx[0]]))*(sum(Observed[...,idx[1]])))/total
print("Expected Matrix : \n", Expected)

X_square = np.empty_like(Observed)
for idx, x in np.ndenumerate(Observed):
    X_square[idx] = (Observed[idx]-Expected[idx])**2/(Expected[idx]) 
print("Chi Square(Xsqr) Matrix : \n", X_square)
chi_square = np.sum(X_square)
print("Chi Square: ",chi_square)

#Degree of Freedom =(Number of Rows-1)*(Number Of Columns-1)
#Find XCrtitical from Chi square table where DF=2 and p=0.05 get value
Xcritical=5.991 #---------------------------------------------------------Change HEre 
if(chi_square<Xcritical):
    print("We accept Null hypothesis")
else:
    print("We Reject Null hypothesis")

Expected Matrix : 
 [[20.24 18.48  5.28]
 [25.76 23.52  6.72]]
Chi Square(Xsqr) Matrix : 
 [[1.63920949 1.62502165 0.01484848]
 [1.28795031 1.27680272 0.01166667]]
Chi Square:  5.855499314350247
We accept Null hypothesis
